source "https://rubygems.org"

# use local theme gem for testing
gem "minimal-ionio-jekyll", path: "../"

# Added by mmistakes 4.19.2
# gem "minimal-mistakes-jekyll", path: "../"
# group :jekyll_plugins do
#   gem 'jekyll-algolia', '~> 1.0'
# end

gem "wdm", "~> 0.1.0" if Gem.win_platform?